### ISSUE TITLE
Adding Api Key

### ISSUE THREAD

**Issue by kushagrasaxenaknit** [Microsoft/Cognitive-Vision-Android#12]
Build the Sample

First, you must obtain a ""Video API subscription key"" by following the instructions on our website.
This does't work.
When I replaced it with "Computer Vision API key" then it worked .
So probably change must me made in Read me instructions if I am right.
Thanks

**Comment by cthrash** [comment]
This has been corrected with the [PR](https://github.com/Microsoft/Cognitive-Vision-Android/pull/24).  Thank you for reporting the issue.
