### ISSUE TITLE
Error executing POST request! Received error code: 401

### ISSUE THREAD

**Issue by IsuruKariyawasam** [Microsoft/Cognitive-Vision-Android#17]
Please Fix this ASAP

**Comment by chsienki** [comment]
Have you checked that the endpoint that you're using matches the region your key was issued for? See #16  for more info.

**Comment by cthrash** [comment]
Please note that for 1.0.394 you must now specify both a subscription ID and API root [here](https://github.com/Microsoft/Cognitive-Vision-Android/blob/master/Sample/app/src/main/res/values/strings.xml#L6).
