### ISSUE TITLE
error illegal character in scheme name 

### ISSUE THREAD

**Issue by zallia2** [Microsoft/Cognitive-Vision-Android#26]
error illegal character in scheme name at index 3: api root is needed e.g. https://westus.api.cognitive.microsoft.com/vision/v1.0/ocr?detectOritentation=true&language=unk

**Comment by cthrash** [comment]
Your api root needs to look like the following [https://westus.api.cognitive.microsoft.com/vision/v1.0](https://github.com/Microsoft/Cognitive-Vision-Android/blob/fcb50eaa6382acf259d3065f17c880080ceeb093/ClientLibrary/lib/src/main/java/com/microsoft/projectoxford/vision/VisionServiceRestClient.java#L56).

**Comment by zallia2** [comment]
private static final String DEFAULT_REGION = "westus";

**Comment by cthrash** [comment]
This repo contains two projects, ClientLibrary and Sample.  If you're just trying things out, you'll want to build the Sample, but change a few values in the [resources](https://github.com/Microsoft/Cognitive-Vision-Android/blob/fcb50eaa6382acf259d3065f17c880080ceeb093/Sample/app/src/main/res/values/strings.xml#L6).

The ClientLibrary is the source for what's in Maven.  Your application will more likely consume this in jar form, and the source is there for reference.   If you do consume the jar directly, you would use it much like the sample app [does](https://github.com/Microsoft/Cognitive-Vision-Android/blob/master/Sample/app/src/main/java/com/microsoft/projectoxford/visionsample/AnalyzeActivity.java#L89).

**Comment by zallia2** [comment]
Ok Thanks

I was wondering are you familiar of how I can join that app software with https://github.com/Azure-Samples/Cognitive-Speech-TTS so that the result of the analyzed image is read out by the text to speech API.  As I was looking to make an app which combined both technologies to help blind people familiarise themselves with certain things by letting them know what it is.

If you can't help can you please direct me to someone who can.

Kind Regards,
Amirsad

**Comment by cthrash** [comment]
Seems like it shouldn't be difficult to copy-paste something like [this](https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/Samples-Http/Android/TTSSample/app/src/main/java/com/microsoft/ttshttpoxford/ttssample/TTSHttpOxfordMainActivity.java) in to your app and send the output of VisionServiceRestClient.describe.

**Comment by zallia2** [comment]
Ok I'll give it a try and let you know how I'm getting on.  

Where is the VisionServiceRestClient.describe. located?

Is that in the VisionServiceRestClient.java file?

Thanks

**Comment by zallia2** [comment]
Can you give me a detailed guide on how I can get that to work?

Thanks

**Comment by cthrash** [comment]
I'm afraid you will do a bit more legwork on your own.   Please post again if you believe there is a defect in the functionality provided, or the way in which it is packaged.

**Comment by zallia2** [comment]
"Seems like it shouldn't be difficult to copy-paste something like this into your app and send the output of VisionServiceRestClient.describe."  Where can I copy that onto the page onto the app of Cognitive-Vision-Android where would be the best place? Also is VisionServiceRestClient.describe. a page or?
