### ISSUE TITLE
Maven Dependency no longer compatible

### ISSUE THREAD

**Issue by erezak** [microsoft/Cognitive-Vision-Android#38]
The binary for com.microsoft.projectoxford:vision requires DefaultHttpClient, which no longer works since SDK 23

**Comment by erezak** [comment]
It works if I downgrade to SDK 25

**Comment by hiSirius** [comment]
it works on my sdk 29.  you have to add the maven setting to the build.grade.
in my case:
```
allprojects {
    repositories {
        jcenter()
         maven {
             url 'https://maven.google.com'
         }
    }
}
```
